### ISSUE TITLE
500 error when creating a vacancy

### ISSUE THREAD

**Issue by anxolerd** [uaprom-summer-2015/Meowth#181]
## Description
Admin console does not restrict user user to create a new vacancy with existing url-name. When user tries to create such vacancy, admin fails with 500 error code.

## STR
1. Go to admin
2. Find out `urlname` of any existing vacancy
3. Try to create a new vacancy with existing url you found out in step 2

## Expected result
Validation error ("vacancy with such url already exists")

## Actual result
Application fails with error code 500 due to unique constraint on `name_in_url` field. (see [[here]](https://github.com/uaprom-summer-2015/Meowth/blob/master/project/models.py#L20))

## Suggestions
Fix `Exists` validator and make it more generic to support different models (related to #180, #182); Than use it on `name_in_url` form field.

**Comment by Cybran111** [comment]
I have been working on  this task. It will be completed on Monday or Tuesday.

**Comment by anxolerd** [comment]
@Cybran111 please contact @akhalyavka -- he is working on #180 which is essential for completing #182 and hence this issue.

**Comment by akhalyavka** [comment]
Look #183

**Comment by Cybran111** [comment]
Fixed in #185

**Comment by anxolerd** [comment]
Not fixed. You used `Exists` validator on the wrong form field. Reopening.

**Comment by anxolerd** [comment]
Also happens on 
- `Category`
- `City`
- `PageChunk`

models

**Comment by akhalyavka** [comment]
Oops.

**Comment by anxolerd** [comment]
@akhalyavka do not worry. =D You did a great job!
@Cybran111  is one who should worry -- he was one who closed issue while it was not resolved.
